import React, { useState, useEffect } from 'react';
import { Speaker, DebatePoint, DebateSession } from '../types';
import { WhisperService } from '../utils/whisperService';
import { AIService } from '../utils/aiService';
import { TTSService } from '../utils/ttsService';
import RecordingPanel from './RecordingPanel';
import DebateFlowTable from './DebateFlowTable';
import HintPanel from './HintPanel';
import RandomTopicSelector from './RandomTopicSelector';
import FinalAnalysis from './FinalAnalysis';
import { ArrowLeft } from 'lucide-react';